### PR TITLE
Release 1.0.4

### PR DESCRIPTION
**Pull request by adiroiban**
## Scope and purpose

To get support for python 3.12 

## How to check

Check the README rendering on https://github.com/twisted/twisted-iocpsupport/tree/release-1.0.4

Check pypi pre-release https://pypi.org/project/twisted-iocpsupport/1.0.4rc1/

### CODE REVIEW

**Comment by adiroiban** [comment]
I think this is ready for review

needs-review

**Comment by adiroiban** [comment]
@pmisik  if you have time, you can try the release candidate with py3.12

I guess that once this is released, we will need to update twisted/twisted

**Review by glyph — APPROVED** [review]

**Comment by adiroiban** [comment]
Thanks @glyph for the review.

Note that the current release is done via the already existing fixed GitHub API token .

I don't have admin permissions for PyPi for twisted-iocpsupport

**Comment by adiroiban** [comment]
1.0.4 available  at https://pypi.org/project/twisted-iocpsupport/

In twisted/twisted this will be used automatically

https://github.com/twisted/twisted/blob/a9ee8e59a5cd1950bf1a18c4b6ca813e5f56ad08/pyproject.toml#L40-L41

**Comment by glyph** [comment]
> Thanks @glyph for the review.
> 
> Note that the current release is done via the already existing fixed GitHub API token .
> 
> I don't have admin permissions for PyPi for twisted-iocpsupport

I rolled out permissions a bit slowly with the org feature on PyPI, but I've started pruning non-org contributors and giving the core team "owner" status on more projects now.  So you should have admin permissions now.

Do you need them to address any current concerns though? My understanding was that the automated PyPI releases on this repo are pretty thorough

**Comment by adiroiban** [comment]
Thanks.

> Do you need them to address any current concerns though? My understanding was that the automated PyPI releases on this repo are pretty thorough

The current API token works and the release was done.

It's just that if it would have stopped working, I would have not had permission to generate a new token.

**Comment by pmisik** [comment]
>@pmisik if you have time, you can try the release candidate with py3.12
>I guess that once this is released, we will need to update twisted/twisted

@adiroiban thank you for incredible fast response.
I tried and reported another issue https://github.com/twisted/twisted/issues/11908
Reported issue generates huge deprecationWarning log for buildbot.
But in the end it seems it hang. At the moment I have no idea why.
In first stage I try to solve deprecation warning issue.

**Comment by adiroiban** [comment]
> But in the end it seems it hang. At the moment I have no idea why.

What hangs ? 

I think that you should be able to run buildbot on Windows without the iocp reactor.
The select reactor should work just fine.

--------

I agree that the deprecationWarning should be fixed in twisted/twisted

Regards

**Pull request merged**
